### ISSUE TITLE
Parse IDs as strings

### ISSUE THREAD

**Issue by jonathancstroud** [MichiganDataScienceTeam/googleanalytics#10]
From the data documentation: "IMPORTANT: Due to the formatting of fullVisitorId you must load the Id's as strings in order for all Id's to be properly unique!"

We currently [let PANDAS do the parsing](https://github.com/MichiganDataScienceTeam/googleanalytics/blob/41b69e184ddff8547e44579383e6d2a005d178ef/dataset.py#L15) and it probably treats these as integers, not strings.

**Comment by ShuaoZhang** [comment]
Just modify it as:

self.train = pd.read_csv(os.path.join(_DATA_DIR, _TRAIN), dtype={"fullVisitorId": str})
self.test = pd.read_csv(os.path.join(_DATA_DIR, _TEST), dtype={"fullVisitorId": str})

**Comment by jonathancstroud** [comment]
Great! Could you submit a pull request with these changes?

Might need to parse the Visit ID abd Session ID this way as well.

**Comment by jonathancstroud** [comment]
Fixed by #11
