### ISSUE TITLE
Pushing to Github using PyCharm

### ISSUE THREAD

**Issue by a-ye13** [MichiganDataScienceTeam/googleanalytics#47]
Can someone who has managed to push to GitHub using PyCharm explain to me how they did it.
Thanks

**Comment by jonathancstroud** [comment]
Pinging @nikunj3107 and @hrxiao who I believe were using pycharm (my apologies if I'm misremembering)

**Comment by jonathancstroud** [comment]
Closing since I think you'll get faster responses on Slack. Let me know if you're still having trouble with this!
