### ISSUE TITLE
Problem in the clone instruction.

### ISSUE THREAD

**Issue by ShuaoZhang** [MichiganDataScienceTeam/googleanalytics#8]
## I believe the instruction in README is somehow wrong. 

When using git bash on WIN10, I think it should be 
### git clone https://github.com/MichiganDataScienceTeam/googleanalytics.git

rather than
### git clone git@github.com:MichiganDataScienceTeam/googleanalytics.git

The later one does not work. However, I'm new in github, so please correct if I made mistake.

**Comment by jonathancstroud** [comment]
Good catch, thanks Shuao. The instructions, as written, assume you have [added an SSH key to your GIthub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/). Could you try completing these steps and see if it works?

Regardless, the instructions should be clarified here. Setting up an SSH key is required to contribute to the repo, so I'll add this step to the contribution instructions.

**Comment by ShuaoZhang** [comment]
Thanks so much. As I said, I'm new to github.

**Comment by jonathancstroud** [comment]
No problem. I'll merge in the fix and close the issue.
